---
- name: Clone fzf repository
  ansible.builtin.git:
    repo: "{{ fzf_repo_url }}"
    dest: "{{ fzf_install_path }}"
    depth: 1
    version: master
  register: fzf_clone

- name: Run fzf installer
  ansible.builtin.command:
    cmd: "{{ fzf_install_path }}/install {{ fzf_install_options | join(' ') }}"
    creates: "{{ ansible_env.HOME }}/.fzf.zsh"
  when: fzf_clone.changed
  notify: Reload shell

- name: Install system packages
  ansible.builtin.apt:
    name: "{{ system_packages }}"
    state: present
